# Generated by Django 5.1.3 on 2024-11-26 17:59

import core.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/user_placeholder.png', upload_to='avatars', validators=[core.models.profile.validate_image]),
        ),
    ]
